name: CI

on:
  pull_request:
    branches:
      - main 
  push:
    branches:
      - main 

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - "3.1"
          - "3.2"
          - "3.3"
          - "3.4"
          - ruby-head
    name: "Ruby ${{ matrix.ruby }}: ${{ matrix.task }}"
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{ matrix.ruby }}"
          bundler-cache: true
      # install castxml for the importer tests
      - run: sudo apt-get update && sudo apt-get install -y castxml
      - run: bundle install
      - run: bundle exec rake spec
